import { DRELineDefinition } from '../types/dre';

export const DRE_LINE_DEFINITIONS: DRELineDefinition[] = [
  {
    key: 'receita_taxa_adm',
    label: 'Receita Taxa de Adm',
    category: 'RECEITA',
    sourceOriginInfo: 'Planilha: RECEITAS TAXA ADM POR PROJETO.xlsx (Aba do projeto)',
    formulaInfo: 'Faturamento bruto da Taxa de Administração contratual',
  },
  {
    key: 'permuta_taxa_adm',
    label: 'Permuta Taxa de Adm',
    category: 'RECEITA',
    sourceOriginInfo: 'Planilha: RECEITAS TAXA ADM POR PROJETO.xlsx (Aba do projeto)',
    formulaInfo: 'Receita de permuta sobre a Taxa de Administração (ex: 30% a 48.81%)',
  },
  {
    key: 'receita_mo_adm',
    label: 'Receita MO Adm Piemonte',
    category: 'RECEITA',
    sourceOriginInfo: 'Planilha: RECEITAS EQUIPE POR PROJETO.xlsx',
    formulaInfo: 'Faturamento repassado da Mão de Obra de Engenharia/Administração',
  },
  {
    key: 'receita_assistencia',
    label: 'Receita Assistência',
    category: 'RECEITA',
    sourceOriginInfo: 'Planilha: RECEITAS TAXA ADM POR PROJETO.xlsx (Aba Assistência)',
    formulaInfo: 'Receitas cobradas por serviços de assistência técnica pós-entrega',
  },
  {
    key: 'impostos',
    label: 'Impostos (PIS + COFINS + ISS)',
    category: 'DESPESA',
    sourceOriginInfo: 'Calculado ou importado da planilha Dados Gerais',
    formulaInfo: 'Fórmula: Receita Bruta Total × Alíquota de Impostos (ex: 9,81%)',
  },
  {
    key: 'despesa_assistencia',
    label: 'Despesa Assistência',
    category: 'DESPESA',
    sourceOriginInfo: 'Planilha: RECEITAS TAXA ADM POR PROJETO.xlsx (Aba Assistência)',
    formulaInfo: 'Custos operacionais com equipes e materiais de assistência técnica',
  },
  {
    key: 'custos_equipe',
    label: 'Custos Equipe',
    category: 'CUSTO',
    sourceOriginInfo: 'Custo Real: Custo de MO POR PROJETO.xlsx | Custo Estimado: Cronograma',
    formulaInfo: 'Custo Real (Folha/Encargos) OU Custo Estimado (Orçamento Mensal × Meses Ativos)',
  },
  {
    key: 'custos_deslocamento',
    label: 'Custos Deslocamento',
    category: 'CUSTO',
    sourceOriginInfo: 'Planilha: Dados gerais contratos.xlsx (Aba Custo Obras)',
    formulaInfo: 'Despesas com logística, viagens e deslocamento de engenharia',
  },
  {
    key: 'margem_bruta_val',
    label: 'MARGEM BRUTA R$',
    category: 'CALCULATED',
    isSubtotal: true,
    isCalculated: true,
    sourceOriginInfo: 'Linha de Subtotal Calculada',
    formulaInfo: 'Fórmula: Receita Bruta Total - (Impostos + Despesa Assistência + Custos Equipe + Custos Deslocamento)',
  },
  {
    key: 'margem_bruta_pct',
    label: 'MARGEM BRUTA %',
    category: 'CALCULATED',
    isCalculated: true,
    sourceOriginInfo: 'Indicador Percentual Calculado',
    formulaInfo: 'Fórmula: (MARGEM BRUTA R$ / Receita Bruta Total) × 100',
  },
  {
    key: 'despesas_adm_pie',
    label: 'Despesas Adm Pie',
    category: 'DESPESA',
    isCalculated: true,
    sourceOriginInfo: 'Motor de Rateio de Despesas ADM',
    formulaInfo: 'Fórmula: Receita Bruta Total × % ADM (Rateio por Receita ou Divisão Simples por Projeto)',
  },
  {
    key: 'resultado',
    label: 'RESULTADO',
    category: 'CALCULATED',
    isSubtotal: true,
    isCalculated: true,
    sourceOriginInfo: 'Resultado Operacional Antes do IRPJ',
    formulaInfo: 'Fórmula: MARGEM BRUTA R$ - Despesas Adm Pie',
  },
  {
    key: 'irpj_csll',
    label: 'IRPJ + CSLL',
    category: 'CALCULATED',
    isCalculated: true,
    sourceOriginInfo: 'Impostos sobre o Lucro Operacional',
    formulaInfo: 'Fórmula: RESULTADO × 10,88% a 15,00% (quando RESULTADO > 0)',
  },
  {
    key: 'resultado_final',
    label: 'Resultado Final',
    category: 'CALCULATED',
    isSubtotal: true,
    isCalculated: true,
    sourceOriginInfo: 'Lucro Líquido Final do Exercício',
    formulaInfo: 'Fórmula: RESULTADO - (IRPJ + CSLL)',
  },
  {
    key: 'margem_liquida_pct',
    label: 'Margem Líquida %',
    category: 'CALCULATED',
    isCalculated: true,
    sourceOriginInfo: 'Margem de Lucratividade Líquida',
    formulaInfo: 'Fórmula: (Resultado Final / Receita Bruta Total) × 100',
  },
  {
    key: 'receita_liquida',
    label: 'RECEITA LÍQUIDA',
    category: 'CALCULATED',
    isCalculated: true,
    sourceOriginInfo: 'Receita Líquida Operacional',
    formulaInfo: 'Fórmula: Receita Bruta Total - Impostos Directos',
  },
  {
    key: 'curva_fisica_obra',
    label: 'CURVA FÍSICA OBRA %',
    category: 'CALCULATED',
    isCalculated: true,
    sourceOriginInfo: 'Cronograma Físico-Financeiro',
    formulaInfo: 'Percentual de avanço físico acumulado da obra no mês',
  },
  {
    key: 'receitas_menos_impostos',
    label: 'RECEITAS - IMPOSTOS',
    category: 'CALCULATED',
    isCalculated: true,
    sourceOriginInfo: 'Entrada Líquida de Receitas',
    formulaInfo: 'Fórmula: Receita Bruta Total - Impostos (PIS + COFINS + ISS)',
  },
];

export const DEFAULT_PROJECTS = [
  'Varanda',
  'Miragio',
  'Aretha',
  'Hall Design',
  'PACE',
  'Vizione',
  'Jardim dos Manacás',
  'Solenne',
  'Reserva Origens',
  'Croma',
  'Unna',
  'Qoya',
  'Líor',
  'Alberi',
  'Amáz',
  'Poty',
  'Vivere',
  'GLB',
  'Platea',
];
